### ISSUE TITLE
cypress:runner is not running the login.feature test

### ISSUE THREAD

**Issue by markhughes321** [JoanEsquivel/cypress-cucumber-boilerplate#1]
- Given I open the Cypress Runner
- When I run the login.feature file 
- Then the test does not run
- And blinks on the screen as seen in the image below

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/9667977/185445760-fe04a79a-05f5-45b5-8169-28b908492101.png">

**Comment by JoanEsquivel** [comment]
Hello, I have download the [last release published ](https://github.com/JoanEsquivel/cypress-cucumber-boilerplate/releases/tag/2.0.0)and it is running fine: 

![image](https://user-images.githubusercontent.com/48256183/185478000-e1fc7bf4-e3c0-4c01-a790-434f27c483e6.png)

**Comment by JoanEsquivel** [comment]
Will close the issue for now. Let me know any further question.

**Comment by markhughes321** [comment]
Thank you very much for the quick reply. When I cloned the repo I was getting that error, however, when downloading the latest release from the zip file it worked just fine. Thanks again 🙌🏽

**Comment by JoanEsquivel** [comment]
Excellent. Weird because cloning it should work, will review it soon to upgrade dependency versions (y)
