### ISSUE TITLE
Run example with multiple tags

### ISSUE THREAD

**Issue by adistoica** [JoanEsquivel/cypress-cucumber-boilerplate#10]
Hello @JoanEsquivel !

Thank you for providing this nice boilerplate! Is there any option to run by using the same command multiple tags? (let's say @mobile and @desktop)

I've had a look over the package.json but couldn't find any example, but only with one tag:
    "cypress:execution-tags": "cypress run --env tags=@mobile",

Thanks

**Comment by Danishs112** [comment]
Hello @adistoica @JoanEsquivel 

Able to run the cypress script through multiple tags:

   "cypress:execution-tags": "cypress run --env tags=@mobile or @desktop",

Thanks
