### ISSUE TITLE
Error after mp4 created

### ISSUE THREAD

**Issue by CHunterGit** [JoanEsquivel/cypress-cucumber-boilerplate#4]
I installed all prerequisites. Verified the standalone formatter was working properly. I get this error after the run:

  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/chunter/source/Cypress10Cuke/cypress-cucumber-boiler    (0 seconds)
                          plate/cypress/videos/login.feature.mp4                                    

An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

Error: spawn cucumber-json-formatter.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-cucumber-boilerplate@2.1.0 cypress:execution: `cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-cucumber-boilerplate@2.1.0 cypress:execution script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chunter/.npm/_logs/2022-09-10T00_04_57_720Z-debug.log

**Comment by JoanEsquivel** [comment]
hello, 

I was not capable to reproduce this behavior.
