### ISSUE TITLE
Generate cucumber html report

### ISSUE THREAD

**Issue by ElibarikiJ** [JoanEsquivel/cypress-cucumber-boilerplate#8]
Can you share command to generate cucumber output report in package json.

**Comment by TranKimHieu** [comment]
step 1: npm i allure-commandline
step 2: add `show-report": "./node_modules/allure-commandline/bin/allure generate ./allure-results --clean  && ./node_modules/allure-commandline/bin/allure open"` to package.json file at scripts object
step 3: npm run cypress:execution-allure
step 4: npm run show-report

**Comment by JoanEsquivel** [comment]
I updated the project with allure already :)

Requirements:
Node JS 
Java 8 

Steps
1- npm i
2- npm run  
3- npm run cypress:execution-allure
4- npm run allure:report
5- allure open

You can replace steps 4 & 5 in your personal repo using the suggested steps by TranKimHieu  #2 & #3 I guess :)
